### ISSUE TITLE
Use case: Find out what process wrote a file

### ISSUE THREAD

**Issue by mewcrazy** [rflament/loggedfs#22]
Hello,

we are having websites which are getting injected with malicious scripts, 8x7ash2hbx8.php and so on. We are trying to find out the root of the problem, so we know exactly what process/script/path a specific file wrote. We have an exact date of file creation and were hoping to use LoggedFS to find it out.

But when we mount the website directory, we get a "Forbidden" on our webserver/website. Is the whole directory not accessable by other processes/users while logging?

Regards,
Dennis

**Comment by rflament** [comment]
hi, what command did you use ? maybe you need the -p parameter

**Comment by mewcrazy** [comment]
Yap, sounds like that was the reason back then. Thank you.

Topic closed
