### ISSUE TITLE
pjdfstest result: loggedfs crashes if a users attempts to perform an operation for a path name exceeding PATH_MAX

### ISSUE THREAD

**Issue by s-m-e** [rflament/loggedfs#7]
I ran the latest [release of ``pjdfstest``](https://github.com/pjd/pjdfstest/tree/d379e7fd28e9075c2d816287bf4b321b8e13a16a) against LoggedFS.

LoggedFS consistently crashes (i.e. does not permit any further operations on it, returning ``ENOTCONN``) after the following tests:

* truncate/03.t
* open/03.t
* mkdir/03.t
* chmod/03.t
* mknod/03.t
* mkfifo/03.t
* unlink/03.t
* symlink/03.t
* link/03.t
* chown/03.t
* ftruncate/03.t
* rmdir/03.t
* rename/02.t

All of those tests have in common that they try to check the behavior of the filesystem when operations with path names exceeded ``PATH_MAX`` characters are attempted. It is expected that the filessystem returns ``ENAMETOOLONG``.

I am running openSUSE Leap 42.3, latest patch-level, Kernel 4.4.103 (-36-default x86_64), fuse 2.9.3 (-11.3.x86_64). The filesystem underneath is ``ext4``. ``PATH_MAX`` for both ``ext4`` and LoggedFS equaled 4096. ``pjdfstest`` was configured for ``ext4``. The filesystem underneath on its own passed all tests.

**Comment by rflament** [comment]
Thanks a lot, I'll have a look

**Comment by s-m-e** [comment]
@rflament You're welcome. I actually figured out the root cause of this issue (and forgot to post it here). It's [the way you construct relative paths](https://github.com/rflament/loggedfs/blob/6a85fbdda5384981cdc60b3982aa2c1cad2c60f0/src/loggedfs.cpp#L106). The extra `./` at the beginning of the string are two characters too many. You can actually solve it by specifying the paths relative to a file handler, allowing you to remove the leading `./` from all relative paths. You'd have to change all syscalls to versions, which support paths relative to file handlers though.
