### ISSUE TITLE
pjdfstest result: loggedfs returns wrong number of hardlinks (n+1) if there is a hardlink on a file

### ISSUE THREAD

**Issue by s-m-e** [rflament/loggedfs#8]
I ran the latest [release of ``pjdfstest``](https://github.com/pjd/pjdfstest/tree/d379e7fd28e9075c2d816287bf4b321b8e13a16a) against LoggedFS.

The test ``link/00.t`` fails the following sub-tests (out of 202 total):

*  8 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,nlink', expected regular,3, got regular,2
*  13 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,mode,nlink,uid,gid', expected regular,0201,3,65534,65533, got regular,0644,2,0,0
*  15 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected regular,0201,3,65534,65533, got regular,0644,3,0,0
*  18 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected regular,0201,2,65534,65533, got regular,0201,3,65534,65533
*  19 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected regular,0201,2,65534,65533, got regular,0644,3,0,0
*  22 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected regular,0201,1,65534,65533, got regular,0201,3,65534,65533
*  34 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,nlink', expected fifo,3, got fifo,2
*  39 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,mode,nlink,uid,gid', expected fifo,0201,3,65534,65533, got fifo,0644,2,0,0
*  41 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected fifo,0201,3,65534,65533, got fifo,0644,3,0,0
*  44 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected fifo,0201,2,65534,65533, got fifo,0201,3,65534,65533
*  45 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected fifo,0201,2,65534,65533, got fifo,0644,3,0,0
*  48 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected fifo,0201,1,65534,65533, got fifo,0201,3,65534,65533
*  60 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,nlink', expected block,3, got block,2
*  65 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,mode,nlink,uid,gid', expected block,0201,3,65534,65533, got block,0644,2,0,0
*  67 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected block,0201,3,65534,65533, got block,0644,3,0,0
*  70 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected block,0201,2,65534,65533, got block,0201,3,65534,65533
*  71 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected block,0201,2,65534,65533, got block,0644,3,0,0
*  74 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected block,0201,1,65534,65533, got block,0201,3,65534,65533
*  86 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,nlink', expected char,3, got char,2
*  91 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,mode,nlink,uid,gid', expected char,0201,3,65534,65533, got char,0644,2,0,0
*  93 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected char,0201,3,65534,65533, got char,0644,3,0,0
*  96 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected char,0201,2,65534,65533, got char,0201,3,65534,65533
*  97 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected char,0201,2,65534,65533, got char,0644,3,0,0
*  100 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected char,0201,1,65534,65533, got char,0201,3,65534,65533
*  112 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,nlink', expected socket,3, got socket,2
*  117 - tried 'lstat pjdfstest_188e97618779bc8797c35c5fd15f763e type,mode,nlink,uid,gid', expected socket,0201,3,65534,65533, got socket,0777,2,0,0
*  119 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected socket,0201,3,65534,65533, got socket,0777,3,0,0
*  122 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected socket,0201,2,65534,65533, got socket,0201,3,65534,65533
*  123 - tried 'lstat pjdfstest_626e9e52477a6690014e2165873670a0 type,mode,nlink,uid,gid', expected socket,0201,2,65534,65533, got socket,0777,3,0,0
*  126 - tried 'lstat pjdfstest_6f3e5f2e79b4b8036844c032342395fd type,mode,nlink,uid,gid', expected socket,0201,1,65534,65533, got socket,0201,3,65534,65533

I attached the corresponding log from LoggedFS: [test_link_00_err_redux.log](https://github.com/rflament/loggedfs/files/1595371/test_link_00_err_redux.log)

I am running openSUSE Leap 42.3, latest patch-level, Kernel 4.4.103 (-36-default x86_64), fuse 2.9.3 (-11.3.x86_64). The filesystem underneath is ``ext4``. It passed all tests.

**Comment by s-m-e** [comment]
Looks like this is a caching issue. It can be fixed by setting ``attr_timeout`` to zero.

**Comment by rflament** [comment]
Indeed, I set the attr_timeout to 0 and it passes the link/00.t tests fine now.
Thanks !
