### ISSUE TITLE
pjdfstest result: setting mtime and atime with nano-second precision fails under certain circumstances - possible bug in FUSE

### ISSUE THREAD

**Issue by s-m-e** [rflament/loggedfs#9]
I ran the latest [release of ``pjdfstest``](https://github.com/pjd/pjdfstest/tree/d379e7fd28e9075c2d816287bf4b321b8e13a16a) against LoggedFS.

The test ``utimensat/02.t`` fails the following sub-tests (out of 10 total):

* 4 - tried 'lstat pjdfstest_5e54ac77641cc205fe486e0bc5946422 atime', expected 1900000000, got 1514739815
* 7 - tried 'lstat pjdfstest_5e54ac77641cc205fe486e0bc5946422 atime', expected 1900000000, got 1514739815
* 8 - tried 'lstat pjdfstest_5e54ac77641cc205fe486e0bc5946422 mtime', expected 1950000000, got 1514739815

I attached the corresponding log from LoggedFS: [test_utimensat_02_err_redux.log](https://github.com/rflament/loggedfs/files/1595376/test_utimensat_02_err_redux.log)

The test ``utimensat/05.t`` fails the following sub-tests (out of 16 total):

* 7 - tried 'lstat pjdfstest_15a42ebdf2336eb173a206f395b33b44 atime', expected 1960000000, got 1514739816
* 8 - tried 'lstat pjdfstest_15a42ebdf2336eb173a206f395b33b44 mtime', expected 1970000000, got 1514739816
* 13 - tried 'lstat pjdfstest_15a42ebdf2336eb173a206f395b33b44 mtime', expected 1970000000, got 1514739816

I attached the corresponding log from LoggedFS: [test_utimensat_05_err_redux.log](https://github.com/rflament/loggedfs/files/1595377/test_utimensat_05_err_redux.log)

I see the exact same tests fail in another FUSE filesystem, so I suspect it's FUSE's fault. The failures are consistent across multiple Linux distributions with Kernels 4.4 to 4.10 with FUSE 2.9.x releases. (The filesystem underneath in every case was ``ext4``. It always passed all tests.) I'd love to have a confirmation though before I file a bug there.

---

*This third issue concludes my series of reports. LoggedFS passed all other tests that ``pjdfstest`` has to offer. Impressive - congratulations.*

**Comment by s-m-e** [comment]
~~The failing of ``utimensat/05.t`` is a caching issue. It can be solved by adding ``attr_timeout``, ``entry_timeout`` and ``negative_timeout`` to the fuse parameters (and setting all of them to zero). It does NOT solve ``utimensat/02.t``, however.~~

**Comment by s-m-e** [comment]
Sry - I should read my notes more carefully. ``utimensat/05.t`` can be fixed, but the problem is another one. It is a path resolution issue. For this test to pass, [``utimes``](https://github.com/rflament/loggedfs/blob/02339be46d316454c7b1db9ae7f4e8facc0a9b7c/src/loggedfs.cpp#L532) must not follow symlinks but change them directly.

**Comment by rflament** [comment]
fixed by https://github.com/rflament/loggedfs/commit/ba5daac909e575c245439cf4d82ad8c16b37f6e3#diff-31ec6257bdec20ba98213f3dcdf1103a

all tests are passing now, thanks for your help !
